export const samplePolls = [
  {
    _id: "3",
    title: "Best Steven Spielberg movie",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "55",
    username: "testuser",
    urlTitle: "best-steven-spielberg-movie",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [],
    comments: [],
  },
  {
    _id: "2",
    title: "Awesome Spielberg Movies",
    urlTitle: "awesome-spielberg-movies",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "55",
    username: "testuser",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [],
    comments: [],
  },
  {
    _id: "10",
    title: "Spielberg!",
    urlTitle: "spielberg",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "2",
    username: "lkalliance",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [],
    comments: [],
  },
  {
    _id: "9",
    title: "Great Directors: Steven Spielberg",
    urlTitle: "great-directors-steven-spielberg",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "2",
    username: "lkalliance",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [],
    comments: [],
  },
  {
    _id: "8",
    title: "Gregleips Nevets",
    urlTitle: "gregleips-nevets",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "55",
    username: "testuser",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [],
    comments: [],
  },
  {
    _id: "17",
    title: "Your pick: best Spielberg film?",
    urlTitle: "your-pick-best-spielberg-film",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "2",
    username: "lkalliance",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [],
    comments: [],
  },
];

export const sampleUser = {
  _id: "55",
  username: "testuser",
  email: "test@test.com",
  polls: [
    {
      poll_id: "3",
      username: "testuser",
      title: "Best Steven Spielberg Movie",
      urlTitle: "xxxxx",
      votes: 22,
      comments: 10,
    },
    {
      poll_id: "2",
      username: "testuser",
      title: "Awesome Spielberg Movies",
      urlTitle: "xxxxx",
      votes: 18,
      comments: 4,
    },
    {
      poll_id: "8",
      username: "testuser",
      title: "Gregleips Nevets",
      urlTitle: "xxxxx",
      votes: 3,
      comments: 2,
    },
  ],
  votes: ["3", "2", "17"],
  comments: [
    {
      poll_id: "3",
      title: "Best Steven Spielberg Movies",
      urlTitle: "xxxxx",
      movie: "Close Encounters of the Third Kind (1977)",
      text: "One of the great films of my youth!",
    },
    {
      poll_id: "17",
      title: "Your pick: best Spielberg film?",
      urlTitle: "xxxxx",
      movie: "Jaws (1975)",
      text: "The Old Men and the Sea and the man-eating nightmare that made me afraid of the water.",
    },
  ],
};
