export const samplePolls = [
  {
    id: "3",
    title: "Best Steven Spielberg movie",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "55",
    username: "testuser",
    urlTitle: "best-steven-spielberg-movie",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [
      {
        id: "1",
        movie: "Jaws (1975)",
        imdb_id: "tt0073195",
        stars: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        plot: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jaws_(film)",
        contentRating: "PG",
        ratings: {
          imDb: "8.1",
          metacritic: "87",
          theMovieDb: "7.7",
          rottenTomatoes: "97",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Adventure, Mystery, Thriller",
        companies: "Zanuck/Brown Productions, Universal Pictures",
        trailer: "https://www.imdb.com/video/imdb/vi4242122009/imdb/embed",
        votes: 0,
      },
      {
        id: "2",
        movie: "Close Encounters of the Third Kind (1977)",
        imdb_id: "tt0075860",
        stars: "Richard Dreyfuss, François Truffaut, Teri Garr",
        plot: "Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO, spurring him to an obsessed cross-country quest for answers as a momentous event approaches.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_Ratio0.6757_AL_.jpg",
        wikipedia:
          "https://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind",
        contentRating: "PG",
        ratings: {
          imDb: "7.6",
          metacritic: "90",
          theMovieDb: "7.4",
          rottenTomatoes: "94",
          filmAffinity: "7.3",
        },
        directors: "Steven Spielberg",
        genres: "Drama, Sci-Fi",
        companies: "Julia Phillips and Michael Phillips Productions, EMI Films",
        trailer: "https://www.imdb.com/video/imdb/vi1849145625/imdb/embed",
        votes: 0,
      },
      {
        id: "3",
        movie: "Schindler's List (1993)",
        imdb_id: "tt0108052",
        stars: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6757_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Schindler%27s_List",
        contentRating: "R",
        ratings: {
          imDb: "9",
          metacritic: "95",
          theMovieDb: "8.6",
          rottenTomatoes: "98",
          filmAffinity: "8.6",
        },
        directors: "Steven Spielberg",
        genres: "Biography, Drama, History",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "ttps://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
        votes: 0,
      },
      {
        id: "4",
        movie: "Jurassic Park (1993)",
        imdb_id: "tt0107290",
        stars: "Sam Neill, Laura Dern, Jeff Goldblum",
        plot: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
        contentRating: "PG-13",
        ratings: {
          imDb: "8.2",
          metacritic: "68",
          theMovieDb: "7.9",
          rottenTomatoes: "91",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Action, Adventure, Sci-Fi",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "https://www.imdb.com/video/imdb/vi177055257/imdb/embed",
        votes: 0,
      },
    ],
    comments: [],
  },
  {
    id: "2",
    title: "Awesome Spielberg Movies",
    urlTitle: "awesome-spielberg-movies",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "55",
    username: "testuser",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [
      {
        id: "1",
        movie: "Jaws (1975)",
        imdb_id: "tt0073195",
        stars: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        plot: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jaws_(film)",
        contentRating: "PG",
        ratings: {
          imDb: "8.1",
          metacritic: "87",
          theMovieDb: "7.7",
          rottenTomatoes: "97",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Adventure, Mystery, Thriller",
        companies: "Zanuck/Brown Productions, Universal Pictures",
        trailer: "https://www.imdb.com/video/imdb/vi4242122009/imdb/embed",
        votes: 0,
      },
      {
        id: "2",
        movie: "Close Encounters of the Third Kind (1977)",
        imdb_id: "tt0075860",
        stars: "Richard Dreyfuss, François Truffaut, Teri Garr",
        plot: "Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO, spurring him to an obsessed cross-country quest for answers as a momentous event approaches.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_Ratio0.6757_AL_.jpg",
        wikipedia:
          "https://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind",
        contentRating: "PG",
        ratings: {
          imDb: "7.6",
          metacritic: "90",
          theMovieDb: "7.4",
          rottenTomatoes: "94",
          filmAffinity: "7.3",
        },
        directors: "Steven Spielberg",
        genres: "Drama, Sci-Fi",
        companies: "Julia Phillips and Michael Phillips Productions, EMI Films",
        trailer: "https://www.imdb.com/video/imdb/vi1849145625/imdb/embed",
        votes: 0,
      },
      {
        id: "3",
        movie: "Schindler's List (1993)",
        imdb_id: "tt0108052",
        stars: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6757_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Schindler%27s_List",
        contentRating: "R",
        ratings: {
          imDb: "9",
          metacritic: "95",
          theMovieDb: "8.6",
          rottenTomatoes: "98",
          filmAffinity: "8.6",
        },
        directors: "Steven Spielberg",
        genres: "Biography, Drama, History",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "ttps://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
        votes: 0,
      },
      {
        id: "4",
        movie: "Jurassic Park (1993)",
        imdb_id: "tt0107290",
        stars: "Sam Neill, Laura Dern, Jeff Goldblum",
        plot: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
        contentRating: "PG-13",
        ratings: {
          imDb: "8.2",
          metacritic: "68",
          theMovieDb: "7.9",
          rottenTomatoes: "91",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Action, Adventure, Sci-Fi",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "https://www.imdb.com/video/imdb/vi177055257/imdb/embed",
        votes: 0,
      },
    ],
    comments: [],
  },
  {
    id: "10",
    title: "Spielberg!",
    urlTitle: "spielberg",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "2",
    username: "lkalliance",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [
      {
        id: "1",
        movie: "Jaws (1975)",
        imdb_id: "tt0073195",
        stars: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        plot: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jaws_(film)",
        contentRating: "PG",
        ratings: {
          imDb: "8.1",
          metacritic: "87",
          theMovieDb: "7.7",
          rottenTomatoes: "97",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Adventure, Mystery, Thriller",
        companies: "Zanuck/Brown Productions, Universal Pictures",
        trailer: "https://www.imdb.com/video/imdb/vi4242122009/imdb/embed",
        votes: 0,
      },
      {
        id: "2",
        movie: "Close Encounters of the Third Kind (1977)",
        imdb_id: "tt0075860",
        stars: "Richard Dreyfuss, François Truffaut, Teri Garr",
        plot: "Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO, spurring him to an obsessed cross-country quest for answers as a momentous event approaches.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_Ratio0.6757_AL_.jpg",
        wikipedia:
          "https://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind",
        contentRating: "PG",
        ratings: {
          imDb: "7.6",
          metacritic: "90",
          theMovieDb: "7.4",
          rottenTomatoes: "94",
          filmAffinity: "7.3",
        },
        directors: "Steven Spielberg",
        genres: "Drama, Sci-Fi",
        companies: "Julia Phillips and Michael Phillips Productions, EMI Films",
        trailer: "https://www.imdb.com/video/imdb/vi1849145625/imdb/embed",
        votes: 0,
      },
      {
        id: "3",
        movie: "Schindler's List (1993)",
        imdb_id: "tt0108052",
        stars: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6757_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Schindler%27s_List",
        contentRating: "R",
        ratings: {
          imDb: "9",
          metacritic: "95",
          theMovieDb: "8.6",
          rottenTomatoes: "98",
          filmAffinity: "8.6",
        },
        directors: "Steven Spielberg",
        genres: "Biography, Drama, History",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "ttps://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
        votes: 0,
      },
      {
        id: "4",
        movie: "Jurassic Park (1993)",
        imdb_id: "tt0107290",
        stars: "Sam Neill, Laura Dern, Jeff Goldblum",
        plot: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
        contentRating: "PG-13",
        ratings: {
          imDb: "8.2",
          metacritic: "68",
          theMovieDb: "7.9",
          rottenTomatoes: "91",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Action, Adventure, Sci-Fi",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "https://www.imdb.com/video/imdb/vi177055257/imdb/embed",
        votes: 0,
      },
    ],
    comments: [],
  },
  {
    id: "9",
    title: "Great Directors: Steven Spielberg",
    urlTitle: "great-directors-steven-spielberg",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "2",
    username: "lkalliance",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [
      {
        id: "1",
        movie: "Jaws (1975)",
        imdb_id: "tt0073195",
        stars: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        plot: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jaws_(film)",
        contentRating: "PG",
        ratings: {
          imDb: "8.1",
          metacritic: "87",
          theMovieDb: "7.7",
          rottenTomatoes: "97",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Adventure, Mystery, Thriller",
        companies: "Zanuck/Brown Productions, Universal Pictures",
        trailer: "https://www.imdb.com/video/imdb/vi4242122009/imdb/embed",
        votes: 0,
      },
      {
        id: "2",
        movie: "Close Encounters of the Third Kind (1977)",
        imdb_id: "tt0075860",
        stars: "Richard Dreyfuss, François Truffaut, Teri Garr",
        plot: "Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO, spurring him to an obsessed cross-country quest for answers as a momentous event approaches.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_Ratio0.6757_AL_.jpg",
        wikipedia:
          "https://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind",
        contentRating: "PG",
        ratings: {
          imDb: "7.6",
          metacritic: "90",
          theMovieDb: "7.4",
          rottenTomatoes: "94",
          filmAffinity: "7.3",
        },
        directors: "Steven Spielberg",
        genres: "Drama, Sci-Fi",
        companies: "Julia Phillips and Michael Phillips Productions, EMI Films",
        trailer: "https://www.imdb.com/video/imdb/vi1849145625/imdb/embed",
        votes: 0,
      },
      {
        id: "3",
        movie: "Schindler's List (1993)",
        imdb_id: "tt0108052",
        stars: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6757_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Schindler%27s_List",
        contentRating: "R",
        ratings: {
          imDb: "9",
          metacritic: "95",
          theMovieDb: "8.6",
          rottenTomatoes: "98",
          filmAffinity: "8.6",
        },
        directors: "Steven Spielberg",
        genres: "Biography, Drama, History",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "ttps://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
        votes: 0,
      },
      {
        id: "4",
        movie: "Jurassic Park (1993)",
        imdb_id: "tt0107290",
        stars: "Sam Neill, Laura Dern, Jeff Goldblum",
        plot: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
        contentRating: "PG-13",
        ratings: {
          imDb: "8.2",
          metacritic: "68",
          theMovieDb: "7.9",
          rottenTomatoes: "91",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Action, Adventure, Sci-Fi",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "https://www.imdb.com/video/imdb/vi177055257/imdb/embed",
        votes: 0,
      },
    ],
    comments: [],
  },
  {
    id: "8",
    title: "Gregleips Nevets",
    urlTitle: "gregleips-nevets",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "55",
    username: "testuser",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [
      {
        id: "1",
        movie: "Jaws (1975)",
        imdb_id: "tt0073195",
        stars: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        plot: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jaws_(film)",
        contentRating: "PG",
        ratings: {
          imDb: "8.1",
          metacritic: "87",
          theMovieDb: "7.7",
          rottenTomatoes: "97",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Adventure, Mystery, Thriller",
        companies: "Zanuck/Brown Productions, Universal Pictures",
        trailer: "https://www.imdb.com/video/imdb/vi4242122009/imdb/embed",
        votes: 0,
      },
      {
        id: "2",
        movie: "Close Encounters of the Third Kind (1977)",
        imdb_id: "tt0075860",
        stars: "Richard Dreyfuss, François Truffaut, Teri Garr",
        plot: "Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO, spurring him to an obsessed cross-country quest for answers as a momentous event approaches.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_Ratio0.6757_AL_.jpg",
        wikipedia:
          "https://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind",
        contentRating: "PG",
        ratings: {
          imDb: "7.6",
          metacritic: "90",
          theMovieDb: "7.4",
          rottenTomatoes: "94",
          filmAffinity: "7.3",
        },
        directors: "Steven Spielberg",
        genres: "Drama, Sci-Fi",
        companies: "Julia Phillips and Michael Phillips Productions, EMI Films",
        trailer: "https://www.imdb.com/video/imdb/vi1849145625/imdb/embed",
        votes: 0,
      },
      {
        id: "3",
        movie: "Schindler's List (1993)",
        imdb_id: "tt0108052",
        stars: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6757_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Schindler%27s_List",
        contentRating: "R",
        ratings: {
          imDb: "9",
          metacritic: "95",
          theMovieDb: "8.6",
          rottenTomatoes: "98",
          filmAffinity: "8.6",
        },
        directors: "Steven Spielberg",
        genres: "Biography, Drama, History",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "ttps://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
        votes: 0,
      },
      {
        id: "4",
        movie: "Jurassic Park (1993)",
        imdb_id: "tt0107290",
        stars: "Sam Neill, Laura Dern, Jeff Goldblum",
        plot: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
        contentRating: "PG-13",
        ratings: {
          imDb: "8.2",
          metacritic: "68",
          theMovieDb: "7.9",
          rottenTomatoes: "91",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Action, Adventure, Sci-Fi",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "https://www.imdb.com/video/imdb/vi177055257/imdb/embed",
        votes: 0,
      },
    ],
    comments: [],
  },
  {
    id: "17",
    title: "Your pick: best Spielberg film?",
    urlTitle: "your-pick-best-spielberg-film",
    description:
      "Here are his greatest hits...which one is the greatest of the greatest?",
    user_id: "2",
    username: "lkalliance",
    created_on: Date(),
    votes: 10,
    user_vote: "1",
    options: [
      {
        id: "1",
        movie: "Jaws (1975)",
        imdb_id: "tt0073195",
        stars: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        plot: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jaws_(film)",
        contentRating: "PG",
        ratings: {
          imDb: "8.1",
          metacritic: "87",
          theMovieDb: "7.7",
          rottenTomatoes: "97",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Adventure, Mystery, Thriller",
        companies: "Zanuck/Brown Productions, Universal Pictures",
        trailer: "https://www.imdb.com/video/imdb/vi4242122009/imdb/embed",
        votes: 0,
      },
      {
        id: "2",
        movie: "Close Encounters of the Third Kind (1977)",
        imdb_id: "tt0075860",
        stars: "Richard Dreyfuss, François Truffaut, Teri Garr",
        plot: "Roy Neary, an Indiana electric lineman, finds his quiet and ordinary daily life turned upside down after a close encounter with a UFO, spurring him to an obsessed cross-country quest for answers as a momentous event approaches.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_Ratio0.6757_AL_.jpg",
        wikipedia:
          "https://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind",
        contentRating: "PG",
        ratings: {
          imDb: "7.6",
          metacritic: "90",
          theMovieDb: "7.4",
          rottenTomatoes: "94",
          filmAffinity: "7.3",
        },
        directors: "Steven Spielberg",
        genres: "Drama, Sci-Fi",
        companies: "Julia Phillips and Michael Phillips Productions, EMI Films",
        trailer: "https://www.imdb.com/video/imdb/vi1849145625/imdb/embed",
        votes: 0,
      },
      {
        id: "3",
        movie: "Schindler's List (1993)",
        imdb_id: "tt0108052",
        stars: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6757_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Schindler%27s_List",
        contentRating: "R",
        ratings: {
          imDb: "9",
          metacritic: "95",
          theMovieDb: "8.6",
          rottenTomatoes: "98",
          filmAffinity: "8.6",
        },
        directors: "Steven Spielberg",
        genres: "Biography, Drama, History",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "ttps://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
        votes: 0,
      },
      {
        id: "4",
        movie: "Jurassic Park (1993)",
        imdb_id: "tt0107290",
        stars: "Sam Neill, Laura Dern, Jeff Goldblum",
        plot: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_Ratio0.6762_AL_.jpg",
        wikipedia: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
        contentRating: "PG-13",
        ratings: {
          imDb: "8.2",
          metacritic: "68",
          theMovieDb: "7.9",
          rottenTomatoes: "91",
          filmAffinity: "7.1",
        },
        directors: "Steven Spielberg",
        genres: "Action, Adventure, Sci-Fi",
        companies: "Universal Pictures, Amblin Entertainment",
        trailer: "https://www.imdb.com/video/imdb/vi177055257/imdb/embed",
        votes: 0,
      },
    ],
    comments: [],
  },
];

export const sampleUser = {
  id: "55",
  username: "testuser",
  email: "test@test.com",
  polls: [
    {
      poll_id: "3",
      username: "testuser",
      title: "Best Steven Spielberg Movie",
      urlTitle: "xxxxx",
      votes: 22,
      comments: 10,
    },
    {
      poll_id: "2",
      username: "testuser",
      title: "Awesome Spielberg Movies",
      urlTitle: "xxxxx",
      votes: 18,
      comments: 4,
    },
    {
      poll_id: "8",
      username: "testuser",
      title: "Gregleips Nevets",
      urlTitle: "xxxxx",
      votes: 3,
      comments: 2,
    },
  ],
  votes: ["3", "2", "17"],
  comments: [
    {
      poll_id: "3",
      title: "Best Steven Spielberg Movies",
      urlTitle: "xxxxx",
      movie: "Close Encounters of the Third Kind (1977)",
      text: "One of the great films of my youth!",
    },
    {
      poll_id: "17",
      title: "Your pick: best Spielberg film?",
      urlTitle: "xxxxx",
      movie: "Jaws (1975)",
      text: "The Old Men and the Sea and the man-eating nightmare that made me afraid of the water.",
    },
  ],
};
